### ISSUE TITLE
Memory issues when using tarFileAtPath

### ISSUE THREAD

**Issue by mwaterfall** [daltoniam/tarkit#12]
It seems that using file system methods should ensure that things are chunked to avoid memory issues, however when taring a 1.5GB file using `tarFileAtPath` I get a huge memory spike up to 500MB+ and then a resulting crash. `compressFileAtPath` also causes this issue. Pretty sure that shouldn't happen so wanted to report it. Any ideas?

**Comment by drallgood** [comment]
Well.. the memory spike is no surprise. We have to handle the data in-memory.

Any details on the crash? A crash log or stack trace would help.

**Comment by mwaterfall** [comment]
It should be a surprise! As mentioned in my issue I use file system methods, and the docs state manages memory properly to support large files. So it shouldn't handle all the date in-memory. 

I've not got any traces available unfortunately as I had to use another library pretty quickly. So I just want to inform the author there are memory issues and can be repro'd if you use the above methods with a 1.5GB directory.

**Comment by drallgood** [comment]
Indeed. What the readme really means to say is that you shouldn't try to keep all files in memory.
But when you're creating the tarfile, they are copied in memory either way.
So you're right. That is wrong.

I've already changed the code so that it writes the tar file in chunks, but I have to test it and also figure out what the performance impact is. Might need to tweak the code a little bit...

**Comment by drallgood** [comment]
Please give this a try and see whether it really works. I cleaned up the whole memory situation a bit so hopefully it's more efficient now :)

**Comment by daltoniam** [comment]
@drallgood thanks for the PR and looking into it. I'll try and test it out with a large file too when I get a moment, been having trouble keeping up with Open Source stuff lately :cry:.

**Comment by vaibhav-jhaveri-ds** [comment]
@mwaterfall Can you please help me with the name of another library you used to zip/unzip tar files?
