### ISSUE TITLE
How to save gzip nsdata to file, if i don't  know name and extension of file?

### ISSUE THREAD

**Issue by DimonDeveloper** [daltoniam/tarkit#6]
How to save gzip nsdata to file, if i don't  know name and extension of file?

**Comment by daltoniam** [comment]
Are you trying to uncompress the gzip data? You would use `+(BOOL)decompressData:(NSData*)data toPath:(NSString*)path error:(NSError**)error` and the `toPath` would be the directory name you want to create.

```objc
NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
NSString* toPath = [[paths objectAtIndex:0] stringByAppendingPathComponent:@"myCoolDirName"];
[DCTar decompressData:yourNSDataObject toPath:toPath error:nil];
```

**Comment by DimonDeveloper** [comment]
I do the same, but only created an empty folder, not a file.

**Comment by daltoniam** [comment]
do you have a gzipped and tar'ed folder, or just a single gzipped file?

**Comment by DimonDeveloper** [comment]
I have just a single gzipped file.

**Comment by daltoniam** [comment]
ah ok. tarkit wasn't specifically designed with that in mind, but you might use `+(NSData*)gzipDecompress:(NSData*)data` and just write the NSData blob to disk with the NSData APIs(e.g. `- (BOOL)writeToFile:(NSString *)path
         atomically:(BOOL)atomically`).
